default: true

# Some services use a linebreak-sensitive renderer, e.g. GitHub comment and BitBucket
line-length: false

no-inline-html: false
no-emphasis-as-heading/no-emphasis-as-header: false
MD036: false

no-trailing-punctuation:
    # Allow headings to end with question mark for FAQ
    punctuation: ".,;:"

# Prettier handles these:
list-marker-space: false
no-multiple-blanks: false
