version: 2
jobs:
    build:
        working_directory: ~/app
        docker:
            - image: circleci/node:12.16.1
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Install Yarn
                  command: "curl -o- -L https://yarnpkg.com/install.sh | bash"
            - run:
                  name: Upgrade
                  command: yarn upgrade --latest
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: yarn install --frozen-lockfile
            - save_cache:
                  name: Save Yarn Package Cache
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
            - run:
                  name: Production React Build
                  command: yarn run build
            - run:
                  name: Build Docker image
                  command: docker build -t $IMAGE_NAME:latest .
            - run:
                  name: Docker Login
                  command: docker login -u $DOCKER_USER -p $DOCKER_PASS $LOGIN_SERVER
            - run:
                  name: Push Docker Image
                  command: docker push $IMAGE_NAME:latest
